'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { decodeShareFragment } from '@/utils/shareLink'

// Read-only viewer for a shared note. The note content is encoded in the
// URL hash fragment (`/share#<b64>`); we decode on mount + render as
// markdown. Hash fragments never reach the server, so the content is
// only visible to whoever has the link.

interface DecodedNote {
  title: string
  content: string
  ts: number
}

export default function SharePage() {
  const [note, setNote] = useState<DecodedNote | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const frag = window.location.hash.slice(1)
    if (!frag) {
      setError('No content found in the link. Make sure you copied the full URL including everything after the # symbol.')
      return
    }
    const decoded = decodeShareFragment(frag)
    if (!decoded) {
      setError('This share link is invalid or was generated by an incompatible version.')
      return
    }
    setNote({ title: decoded.title, content: decoded.content, ts: decoded.ts })
    // Set the document title so the browser tab is meaningful.
    document.title = `${decoded.title} — Shared via Noteser`
  }, [])

  if (error) {
    return (
      <div className="min-h-screen bg-obsidianBlack text-obsidianText flex items-center justify-center p-8">
        <div className="max-w-md text-center space-y-4">
          <h1 className="text-2xl font-medium">Couldn&apos;t open this note</h1>
          <p className="text-obsidianSecondaryText">{error}</p>
          <Link href="/" className="inline-block px-4 py-2 bg-obsidianAccentPurple/20 text-obsidianAccentPurple rounded hover:bg-obsidianAccentPurple/30">
            Go to Noteser
          </Link>
        </div>
      </div>
    )
  }

  if (!note) {
    return (
      <div className="min-h-screen bg-obsidianBlack text-obsidianSecondaryText flex items-center justify-center">
        <div>Decoding…</div>
      </div>
    )
  }

  const generatedDate = new Date(note.ts).toLocaleDateString(undefined, {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  return (
    <div className="min-h-screen bg-obsidianBlack text-obsidianText">
      <header className="border-b border-obsidianBorder px-6 py-4 flex items-center justify-between bg-obsidianBlack/80 backdrop-blur sticky top-0 z-10">
        <div>
          <div className="text-xs text-obsidianSecondaryText">Shared via Noteser · {generatedDate}</div>
          <h1 className="text-xl font-medium">{note.title}</h1>
        </div>
        <Link
          href="/"
          className="text-sm px-3 py-1.5 bg-obsidianAccentPurple/15 text-obsidianAccentPurple border border-obsidianAccentPurple/40 rounded hover:bg-obsidianAccentPurple/25 transition-colors"
        >
          Open Noteser →
        </Link>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-8">
        <article className="prose prose-invert max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {note.content || '*This note is empty.*'}
          </ReactMarkdown>
        </article>
      </main>
      <footer className="border-t border-obsidianBorder px-6 py-4 text-xs text-obsidianSecondaryText text-center">
        Read-only view. The content lives in the URL — anyone with this link can read it.
      </footer>
    </div>
  )
}
