/**
 * ensureFolderPath.test.ts
 *
 * Verifies that `useFolderStore.ensureFolderPath` stores SANITIZED folder
 * names so the path generated by the GitHub push step round-trips against
 * what the remote already has. Storing the raw segment was the root cause
 * of the "every sync uploads every blob" storm — `Daily Notes` (raw) →
 * `Daily-Notes` (sanitized) at push time = path mismatch = re-upload.
 */

jest.mock('idb-keyval', () => ({
  get: jest.fn().mockResolvedValue(undefined),
  set: jest.fn().mockResolvedValue(undefined),
  del: jest.fn().mockResolvedValue(undefined),
}))

import { useFolderStore } from '../stores/folderStore'

beforeEach(() => {
  useFolderStore.setState({ folders: [], activeFolderId: null, expandedFolders: {} })
})

describe('ensureFolderPath — stores sanitized names', () => {
  test('a single segment with spaces is stored as the sanitized form', () => {
    useFolderStore.getState().ensureFolderPath(['Daily Notes'])
    const folders = useFolderStore.getState().folders
    expect(folders).toHaveLength(1)
    expect(folders[0].name).toBe('Daily-Notes')
  })

  test('nested segments each get sanitized independently', () => {
    useFolderStore.getState().ensureFolderPath(['My Notes', 'Sub Folder', 'Deep One'])
    const names = useFolderStore.getState().folders.map(f => f.name)
    expect(names).toEqual(['My-Notes', 'Sub-Folder', 'Deep-One'])
  })

  test('subsequent calls with the same raw path REUSE the existing folder', () => {
    const first  = useFolderStore.getState().ensureFolderPath(['Daily Notes'])
    const second = useFolderStore.getState().ensureFolderPath(['Daily Notes'])
    expect(first).toBe(second)
    expect(useFolderStore.getState().folders).toHaveLength(1)
  })

  test('subsequent call with the sanitized form REUSES the existing folder', () => {
    // This is the regression that mattered most: "Daily Notes" and
    // "Daily-Notes" must resolve to the same folder so we don't create a
    // duplicate every cycle.
    const fromRaw       = useFolderStore.getState().ensureFolderPath(['Daily Notes'])
    const fromSanitized = useFolderStore.getState().ensureFolderPath(['Daily-Notes'])
    expect(fromRaw).toBe(fromSanitized)
    expect(useFolderStore.getState().folders).toHaveLength(1)
  })

  test('segments that need no sanitization are stored verbatim', () => {
    useFolderStore.getState().ensureFolderPath(['Notes', 'Personal'])
    const names = useFolderStore.getState().folders.map(f => f.name)
    expect(names).toEqual(['Notes', 'Personal'])
  })

  test('empty segments list returns null and creates no folder', () => {
    expect(useFolderStore.getState().ensureFolderPath([])).toBeNull()
    expect(useFolderStore.getState().folders).toHaveLength(0)
  })
})
