/**
 * Per-request Content-Security-Policy builder. Finding 6 of the 2026-05-21
 * security audit: the old CSP shipped a *static* header with
 * `script-src 'self' 'unsafe-inline'`, which defeats the purpose of a CSP —
 * an injected inline <script> would execute. We replace it with a
 * per-request nonce emitted from middleware (`src/middleware.ts`):
 *
 *   script-src 'self' 'nonce-<random>' 'strict-dynamic'
 *
 * `'strict-dynamic'` lets Next's nonced bootstrap scripts load the rest of
 * the bundle without us having to enumerate every chunk URL; modern browsers
 * then ignore the `'self'` host-source fallback, so 'self' is kept only for
 * the (legacy) browsers that don't understand 'strict-dynamic'.
 *
 * 'unsafe-eval' is added ONLY in non-production (Next dev HMR / React
 * Refresh). Production drops it: React/Next ship no eval in their prod
 * bundles and the CodeMirror stack we use does not construct Functions at
 * runtime, so dropping it neutralises eval-based XSS even if an injection
 * slips through.
 *
 * style-src keeps 'unsafe-inline' on purpose — Tailwind, styled-jsx and
 * CodeMirror (EditorView.baseTheme) all inject inline <style>. Nonce-ing
 * styles would break the editor and the whole theme, so we do not.
 */

/**
 * Derive a single WS origin from a raw NEXT_PUBLIC_YJS_WS_URL value so the
 * CSP only allows the collaboration server the operator opted into. Anything
 * malformed (or unset) collapses to `null` ("no WS connections at all") —
 * the bare `wss: ws:` wildcards (Finding 5) would let an XSS payload
 * exfiltrate localStorage to any host.
 */
export function deriveCollabWsOrigin(raw: string | undefined): string | null {
  if (!raw) return null
  try {
    const url = new URL(raw)
    if (url.protocol !== 'ws:' && url.protocol !== 'wss:') return null
    return `${url.protocol}//${url.host}`
  } catch {
    return null
  }
}

export interface BuildCspOptions {
  /** Non-production (dev / test): adds 'unsafe-eval' to script-src. */
  isDev: boolean
  /** Already-derived ws(s):// origin to add to connect-src, or null. */
  wsOrigin: string | null
}

/**
 * Build the full CSP header value for a single request.
 *
 * @param nonce base64 per-request nonce (already generated by middleware).
 */
export function buildCsp(nonce: string, options: BuildCspOptions): string {
  const { isDev, wsOrigin } = options

  const scriptSrc = [
    "'self'",
    `'nonce-${nonce}'`,
    "'strict-dynamic'",
    ...(isDev ? ["'unsafe-eval'"] : []),
  ].join(' ')

  const connectSrc = [
    "'self'",
    'https://api.github.com',
    'https://github.com',
    'https://api.anthropic.com',
    'https://api.openai.com',
    ...(wsOrigin ? [wsOrigin] : []),
  ].join(' ')

  return [
    "default-src 'self'",
    `script-src ${scriptSrc}`,
    // Keep 'unsafe-inline' for styles: Tailwind / styled-jsx / CodeMirror
    // all inject inline <style>. Do NOT nonce styles.
    "style-src 'self' 'unsafe-inline'",
    // User notes can ![]() any HTTPS image. data:/blob: for attachments.
    "img-src 'self' data: blob: https:",
    "font-src 'self' data:",
    // Browser-direct API surfaces: github.com for OAuth fallbacks, the
    // GitHub Git Data API, Anthropic + OpenAI for BYO-key AI features.
    // The optional Yjs collab server is added only when
    // NEXT_PUBLIC_YJS_WS_URL is a valid ws:// or wss:// URL.
    `connect-src ${connectSrc}`,
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
  ].join('; ')
}
